// <auto-generated />
using System;
using ControleFinanceiro_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleFinanceiro_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322035231_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleFinanceiro_Backend.Models.Conta", b =>
                {
                    b.Property<int>("cdConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cdConta"));

                    b.Property<int>("cdTipoConta")
                        .HasColumnType("integer");

                    b.Property<DateTime>("dtCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nmConta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("vlSaldoAtual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("vlSaldoInicial")
                        .HasColumnType("numeric");

                    b.HasKey("cdConta");

                    b.ToTable("Contas");
                });
#pragma warning restore 612, 618
        }
    }
}
