// <auto-generated />
using System;
using ControleFinanceiro_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleFinanceiro_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322150000_AddAutenticacao")]
    partial class AddAutenticacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // ── Usuarios ─────────────────────────────────────────────
            modelBuilder.Entity("ControleFinanceiro_Backend.Models.Usuario", b =>
            {
                b.Property<int>("cdUsuario").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
                b.Property<string>("nmUsuario").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("dsEmail").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("dsSenhaHash").IsRequired().HasColumnType("text");
                b.Property<string>("dsRefreshToken").HasColumnType("text");
                b.Property<DateTime?>("dtRefreshTokenExpira").HasColumnType("timestamp with time zone");
                b.Property<bool>("ativo").HasColumnType("boolean");
                b.Property<DateTime>("dtCriacao").HasColumnType("timestamp with time zone");
                b.HasKey("cdUsuario");
                b.HasIndex("dsEmail").IsUnique();
                b.ToTable("Usuarios");
            });

            // ── Contas ───────────────────────────────────────────────
            modelBuilder.Entity("ControleFinanceiro_Backend.Models.Conta", b =>
            {
                b.Property<int>("cdConta").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
                b.Property<int>("cdUsuario").HasColumnType("integer");
                b.Property<int>("cdTipoConta").HasColumnType("integer");
                b.Property<string>("nmConta").IsRequired().HasColumnType("text");
                b.Property<decimal>("vlSaldoInicial").HasColumnType("numeric");
                b.Property<decimal>("vlSaldoAtual").HasColumnType("numeric");
                b.Property<DateTime>("dtCriacao").HasColumnType("timestamp with time zone");
                b.HasKey("cdConta");
                b.HasIndex("cdUsuario");
                b.ToTable("Contas");
            });

            // ── Categorias ───────────────────────────────────────────
            modelBuilder.Entity("ControleFinanceiro_Backend.Models.Categoria", b =>
            {
                b.Property<int>("cdCategoria").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
                b.Property<int>("cdUsuario").HasColumnType("integer");
                b.Property<string>("nmCategoria").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("dsCategoria").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<string>("tpCategoria").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<string>("icone").HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<string>("cor").HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<bool>("ativo").HasColumnType("boolean");
                b.Property<DateTime>("dtCriacao").HasColumnType("timestamp with time zone");
                b.HasKey("cdCategoria");
                b.HasIndex("cdUsuario");
                b.ToTable("Categorias");
            });

            // ── Metas ────────────────────────────────────────────────
            modelBuilder.Entity("ControleFinanceiro_Backend.Models.Meta", b =>
            {
                b.Property<int>("cdMeta").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
                b.Property<int>("cdUsuario").HasColumnType("integer");
                b.Property<string>("nmMeta").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)");
                b.Property<string>("dsMeta").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<decimal>("vlAlvo").HasColumnType("numeric");
                b.Property<decimal>("vlAtual").HasColumnType("numeric");
                b.Property<DateTime>("dtPrazo").HasColumnType("timestamp with time zone");
                b.Property<bool>("ativo").HasColumnType("boolean");
                b.Property<DateTime>("dtCriacao").HasColumnType("timestamp with time zone");
                b.HasKey("cdMeta");
                b.HasIndex("cdUsuario");
                b.ToTable("Metas");
            });

            // ── Transacoes ───────────────────────────────────────────
            modelBuilder.Entity("ControleFinanceiro_Backend.Models.Transacao", b =>
            {
                b.Property<int>("cdTransacao").ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
                b.Property<int>("cdUsuario").HasColumnType("integer");
                b.Property<string>("tpTransacao").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<int>("cdConta").HasColumnType("integer");
                b.Property<int?>("cdContaDestino").HasColumnType("integer");
                b.Property<int?>("cdCategoria").HasColumnType("integer");
                b.Property<decimal>("vlTransacao").HasColumnType("numeric");
                b.Property<DateTime>("dtTransacao").HasColumnType("timestamp with time zone");
                b.Property<string>("dsTransacao").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<DateTime>("dtCriacao").HasColumnType("timestamp with time zone");
                b.HasKey("cdTransacao");
                b.HasIndex("cdUsuario");
                b.HasIndex("cdConta");
                b.HasIndex("cdContaDestino");
                b.HasIndex("cdCategoria");
                b.ToTable("Transacoes");
            });

            // ── Relacionamentos ──────────────────────────────────────
            modelBuilder.Entity("ControleFinanceiro_Backend.Models.Conta", b =>
            {
                b.HasOne("ControleFinanceiro_Backend.Models.Usuario", "Usuario")
                    .WithMany().HasForeignKey("cdUsuario").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("ControleFinanceiro_Backend.Models.Categoria", b =>
            {
                b.HasOne("ControleFinanceiro_Backend.Models.Usuario", "Usuario")
                    .WithMany().HasForeignKey("cdUsuario").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("ControleFinanceiro_Backend.Models.Meta", b =>
            {
                b.HasOne("ControleFinanceiro_Backend.Models.Usuario", "Usuario")
                    .WithMany().HasForeignKey("cdUsuario").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("ControleFinanceiro_Backend.Models.Transacao", b =>
            {
                b.HasOne("ControleFinanceiro_Backend.Models.Usuario", "Usuario")
                    .WithMany().HasForeignKey("cdUsuario").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("ControleFinanceiro_Backend.Models.Conta", "Conta")
                    .WithMany().HasForeignKey("cdConta").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("ControleFinanceiro_Backend.Models.Conta", "ContaDestino")
                    .WithMany().HasForeignKey("cdContaDestino").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("ControleFinanceiro_Backend.Models.Categoria", "Categoria")
                    .WithMany().HasForeignKey("cdCategoria").OnDelete(DeleteBehavior.SetNull);
            });

#pragma warning restore 612, 618
        }
    }
}
